package com.argo.admin;

public enum AuditAction {
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGIN_LOCKED,
	LOGOUT,
	ACCESS_DENIED,
	ACCOUNT_CREATED,
	CARD_EXTRA_DISCOUNT_UPDATE,
	CARD_SET_ON_SALE_UPDATE,
	CARD_SET_EXTRA_DISCOUNT_UPDATE,
	IP_BLOCKED,
	IP_UNBLOCKED,
	AUDIT_LOG_VIEWED
}
